AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An Amazon SES notification handler for processing bounces, complaints and
  deliveries.
Parameters:
  bucket:
    Type: String
    Description: S3 Bucket
Resources:
  SESNotificationToS3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: >-
        An Amazon SES notification handler for processing bounces, complaints
        and deliveries.
      MemorySize: 128
      Timeout: 10
      Tags:
        'lambda-console:blueprint': ses-notification-python
      Environment:
        Variables: 
          BUCKET: !Ref bucket
