AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An Amazon SES notification handler for processing bounces, complaints and
  deliveries.
Resources:
  ses-notification-to-s3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: >-
        An Amazon SES notification handler for processing bounces, complaints
        and deliveries.
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::365464100180:role/service-role/ses-notification-to-s3'
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic1
      Tags:
        'lambda-console:blueprint': ses-notification-python
      Environment:
        Variables: 
          S3_BUCKET: bucket-name
  SNSTopic1:
    Type: 'AWS::SNS::Topic'
