name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: apex/actions/aws/sam@master
      with:
        args: package --template-file app-spec.yml --output-template-file out.yml --s3-bucket ses-notification-to-s3
      env:
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ap-northeast-1
        AWS_DEFAULT_OUTPUT: json

  build_notification:

    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
    - name: Build Notification
      uses: apex/actions/slack@master
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:

    runs-on: ubuntu-latest
    
    needs: build

    steps:
    - uses: actions/checkout@master
    - name: Deploy
      uses: apex/actions/aws/sam@master
      with:
        args: deploy --stack-name sestest --capabilities CAPABILITY_IAM --template-file out.yml
      env:
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ap-northeast-1
        AWS_DEFAULT_OUTPUT: json

  deploy_notification:

    runs-on: ubuntu-latest

    needs: deploy

    steps:
    - name: Deploy Notification
      uses: apex/actions/slack@master
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
